name: build and push to dockerhub

on:
  push:
    branches:
      - master
      - 'releases/**'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
env:
  image: whosydd/netease-cloud-music-api
  released_tag: latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Get tag from package version
        uses: whosydd/tag-from-version@v0.1.1
        id: tagName
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          # 添加dockerhub登录信息
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          #tags: whosydd/netease-cloud-music-api:latest
          tags: >-
              ${{ env.image }}:${{ env.released_tag }},
              ${{ env.image }}:${{ steps.tagName.outputs.tag }}
